version: 2

project_name: tmuxai

before:
  hooks:
    - go mod download
    - go generate ./...

release:
  prerelease: false

env:
  - CGO_ENABLED=0

builds:
  - id: linux
    goos:
      - linux
    goarch:
      - amd64
      - arm
    goarm:
      - 7
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/debjan/tmuxai/internal.Version=v{{.Version}}
      - -s -w -X github.com/debjan/tmuxai/internal.Commit={{.Commit}}
      - -s -w -X github.com/debjan/tmuxai/internal.Date={{.Date}}

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.sha256"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^tasks:"

nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    maintainer: alvinunreal
    homepage: https://tmuxai.dev
    description: AI-Powered, Non-Intrusive Terminal Assistant
    license: "Apache-2.0"
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/tmuxai/copyright
        file_info:
          mode: 0644
